#!/bin/bash

CLR_YLW="\033[1;33m"
CLR_GRN="\033[1;32m"
CLR_RST="\033[0m"

STYLE="file:.clang-format"
if [ -n "${STYLE}" ] ; then
  STYLEARG="-style=${STYLE}"
else
  STYLEARG=""
fi

format_file() {
  file="${1}"
  if [ -f $file ]; then
    echo -e "${CLR_GRN}Formatting ${file}${CLR_RST}"
    clang-format -i ${STYLEARG} ${1}
    git add ${1}
  fi
}

case "${1}" in
  --about )
    echo "Runs clang-format on source files"
    ;;
  * )
    echo -e "${CLR_YLW}Running clang-format on staged files${CLR_RST}"
    for file in `git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp)$' ` ; do
      format_file "${file}"
    done
    ;;
esac
